### PR TITLE
Bruker showcase

### PR DESCRIPTION
**Pull request by tleissner**
## Describe your contribution

This notebook showcases the volume reconstruction of microCT projection data obtained with a *Bruker Skyscan 2214* using a flat panel detector and a source voltage of 125 kV at 69 µA. Projections are available as 16-bit tiffs. 

**All files created during a scan are located in a single flat folder. The image normalisation using is baked into the images.**

Four test data sets are provided:

<p>
    
- **01-switch-small**: a 360 deg scan of a pushbutton switch (binning 4x4)
- **02-switch-large**: a 360 deg scan of a pushbutton switch (no binning)
- **03-coffee**: a 180 deg scan of a coffee bean
- **04-citron**: a 180 deg scan of a citron

The data sets are available a compressed zip archives on [DOI](https://doi.org/10.5281/zenodo.11258475)

## Checklist when you are ready to request a review

- [x ] I have performed a self-review of my code
- [x ] I have created a new folder, containing my contributions which are in the form of jupyter notebooks, with any necessary supporting python files, and a LICENSE file.
- [x ] I have added a description of my contribution(s) to the top of my file(s)
- [x ] If publicly available, I have added a link to the dataset used near the top of my file(s)
- [x ] I have added the CIL version I ran with near the top of my file(s)
- [x ] The content of this Pull Request (the Contribution) is intentionally submitted for inclusion in CIL-User-Showcase.
- [x ] I confirm that the contribution does not violate any intellectual property rights of third parties.
- [x ] I confirm that I have added license headers to all of the files I am contributing (with a license of my choice)
- [ ] Change pull request label to 'Waiting for review' 

Note: for an example of a contribution, where a license header, description, data link and CIL version has been added, please
see: [example_contribution](https://github.com/TomographicImaging/CIL-User-Showcase/blob/main/example_contribution)

### CODE REVIEW

**Comment by MargaretDuff** [comment]
Hi @tleissner - Thank-you so much for your work on this! It is a great example of writing your own reader. The datasets are also interesting and may be useful for other users. 

I made a few, very small edits. I will now ask @jakobsj to take a look and, hopefully, we can get it merged soon!

**Review by jakobsj — CHANGES_REQUESTED** [review]
Many thanks @tleissner, the notebook reads really well and provides and comprehensive overview of getting a Bruker dataset set up and reconstructed. Thanks @MargaretDuff for editing.  I only had two requests:
- I don't understand the sentence in the introduction that image normalization is "baked into" the images, possibly also something about the sentence structure does not look right to me.  Could I ask this sentence to be rephrased and elaborated.
- For the final images I'd recommend switching the colormap to a simpler one that is sequential, see eg https://matplotlib.org/stable/users/explain/colors/colormaps.html

**Comment by tleissner** [comment]
I have updated the notebooks :). Do I have to create a new pull request or do something else? I am not so familiar with the GitHub workflow.

**Comment by MargaretDuff** [comment]
Thanks @tleissner. That's great and no, you don't have to put in another PR, you pushed to your branch and that is sufficient.

**Review by MargaretDuff — APPROVED** [review]
Excellent contribution!

**Comment by MargaretDuff** [comment]
@jakobsj  - I have just reran the notebook so the order starts at 1. If you are happy, can you approve?

**Comment by jakobsj** [comment]
Very happy with the changes!  Only one question after looking through again - the final reconstructions appear slightly blurred, especially the four internal features in the horizontal slice. Sometimes this cannot be avoided, but compared to the projections, and the sinogram of the same slice 243, those features appear somewhat sharper in the projections than in the final reconstruction.  This could be a result of not having the geometry perfectly set up, but not sure.  To understand this issue better, could you perhaps include some more horizontal slices?  Is there a reconstruction produced by the instrument software to compare with, if so one could also include that in the notebook to validate that the CIL-based workflow works.

 I suppose in addition there is a beam-hardening effect (outer white ring and internal dark stripes between four features) which is harder to do something about. I suggest simply keeping that as is.

**Comment by MargaretDuff** [comment]
With COR correction: 
image
Without COR correction: 
image

**Comment by MargaretDuff** [comment]
I would be tempted to leave the CoR processor in: 
- With CoR: 
image

- Difference between the two images: 
image

**Comment by tleissner** [comment]
> I would be tempted to leave the CoR processor in:

I agree, just removed it because of running out of memory on my the computer yesterday. 

I will prepare some comparison with the proprietary software. That one utilises some reference scans for alignment, so expect it give better results out of the box.

**Comment by tleissner** [comment]
I fixed my CUDA issues and could finally run the CoR processor. I have added some features for interactive plotting to the showcase notebook. Finally, I created another notebook to compare the CIL results with the commercial software. In both cases I just applied some CoR correction.

**Comment by jakobsj** [comment]
Thanks for adding this @tleissner! Unfortunately I don't see the images comparing CIL and the commercial software in the notebook
https://github.com/tleissner/CIL-User-Showcase/blob/main/010_reconstruct_BrukerSkyscan_data/compare-CIL-NRecon.ipynb
perhaps can you try with some more basic non-interactive plot types, such as show2D used in the other notebooks? Thanks!

**Comment by jakobsj** [comment]
Looking at the additional examples (again thank you so much for adding all of these, that is super useful!) I can't help thinking something is still off with the geometry. Notably the sample04 / lemon case the final reconstruction shows some fairly prominent artifacts, almost duplicating some features. One common suspect in such cases is the acquisition rotation direction which may need to be specified as reversed. Could you check this by including a minus sign on your angles?

**Comment by MargaretDuff** [comment]
With the angles as they currently are: 
image
 with an extra minus sign
 ```python
    # Create AcquisitionGeometry object
    ag = AcquisitionGeometry.create_Cone3D(source_position=[0,-distance_source_origin,0],detector_position=[0,distance_origin_detector,0],
                                       detector_direction_x=[1,0,0],detector_direction_y=[0,0,1]
                                      )\
    .set_panel(num_pixels=[detector_cols,detector_rows], pixel_size = detector_pixel_size)\
    .set_angles(angles=-theta_deg)

    return ag

```
image

I don't see much difference

**Comment by MargaretDuff** [comment]
I also couldn't open the Bruker reconstructed data because don't have options to unzip 7z files on my virtual machine. Is there a way of putting it on Zenodo in a zip file for ease of use?

**Comment by tleissner** [comment]
> I also couldn't open the Bruker reconstructed data because don't have options to unzip 7z files on my virtual machine. Is there a way of putting it on Zenodo in a zip file for ease of use?

@MargaretDuff  I have uploaded the datasets to Zenodo as zip files and added a link to the notebook: https://doi.org/10.5281/zenodo.12205501

**Comment by tleissner** [comment]
> Thanks for adding this @tleissner! Unfortunately I don't see the images comparing CIL and the commercial software in the notebook https://github.com/tleissner/CIL-User-Showcase/blob/main/010_reconstruct_BrukerSkyscan_data/compare-CIL-NRecon.ipynb perhaps can you try with some more basic non-interactive plot types, such as show2D used in the other notebooks? Thanks!

@jakobsj: I have added a series of static plots using Matplotlib.

**Comment by MargaretDuff** [comment]
Many thanks, @tleissner! I have added some wget instructions and rescaled the plots in the comparison notebook to compare the results. The machine reconstruction has some beam hardening correction and a process for removing negative values but I don't think it is worth replicating these in CIL, because that is not the purpose of this showcase. 

@jakobsj - have you any further ideas on the blurriness?

**Comment by jakobsj** [comment]
I think the main example notebook is looking good and is ready.  

For the lemon notebook, the artifacts remain - it seems center of rotation was switched off for this one? I'm okay with it being like this, perhaps with a quick comment added that one can switch on the various corrections if wanting to improve the reconstruction.

THanks for adding the comparison to vendor software.  I can't see any major difference, perhaps a bit on the left images. Good to show a range of images allowing a comparison on many slices, they are currently quite small though, low resolution, so it is difficult to appreciate and compare in detail - though perhaps good enough for the purpose. You could consider enlarging though I'm also happy to see merged if you choose not to.

Thanks once again!

**Comment by MargaretDuff** [comment]
Before CoR corrector: 
image
with CoR corrector:
image
Not much different

**Comment by MargaretDuff** [comment]
Some improvements with scaling the final image and a slightly larger ROI 
image

**Comment by MargaretDuff** [comment]
@jakobsj and @tleissner - are you happy for me to merge?

**Review by jakobsj — APPROVED** [review]
Yes I'm happy!  Thanks for investigating a bit more.  I think for the purpose of the user showcase notebook, that is in great shape and fully, and comprehensively, conveys how one may load, set up and reconstruct a Bruker dataset, and by example, how one may approach other data formats.  For the lemon and further comparison with the vendor recons, that can be something to look more into later as part of integrating a Bruker data reader into the core CIL codebase.

**Comment by tleissner** [comment]
Thanks for the valuable feedback and improvements, @MargaretDuff  and @jakobsj. I have been busy with exams these days and didn't had a chance to investigate the issues further. I will keep working on the notebook to see whether the reconstruction quality can be improved.

**Comment by jakobsj** [comment]
Thank you @tleissner - I think from our perspective the notebooks are in great shape and almost reproduce the vendor quality. We wouldn't mind postponing further optimization until the time comes to integrate the bruker code into a proper reader, but of course you have to be happy with the notebooks as well :)   We were wondering if you'd happen to have some photographs of the samples used in each of the notebooks? Just because having access to those as "ground truths" could be quite helpful to debug CIL geometry issues, such as mirroring and misalignment. For the lemon for example I suppose it would be the most useful with pictures of the lemon cut in halves for example to see some features, though photographs just from the outside are also helpful. If so, it would be great if you could add those to each of the notebooks.

**Comment by tleissner** [comment]
Thanks for the kind words, @jakobsj, for now I am fine with the quality of the notebooks, too, and leave it up to you to merge it or to wait. I will try to add some images otherwise in August.

**Comment by MargaretDuff** [comment]
Thank you @tleissner - I will merge it now but we can always change it in the future if you have some additional images.

**Pull request merged**
