### PR TITLE
Hyperspectral notebook from Cambridge hackathon communicated by Jakob Sauer Jørgensen

### PR DESCRIPTION
**Pull request by IdaPug**
## Describe your contribution
Notebook using a hyperspectral dataset to perform spatial and spectral regularised reconstruction using CIL. 
Please note I'm unsure which license to add. I am using ASTRA.

## Checklist when you are ready to request a review

- [x ] I have performed a self-review of my code
- [x ] I have created a new folder, containing my contributions which are in the form of jupyter notebooks, with any necessary supporting python files, and a LICENSE file.
- [ ] I have added a description of my contribution(s) to the top of my file(s)
- [x ] If publicly available, I have added a link to the dataset used near the top of my file(s)
- [x ] I have added the CIL version I ran with near the top of my file(s)
- [x ] The content of this Pull Request (the Contribution) is intentionally submitted for inclusion in CIL-User-Showcase.
- [ x] I confirm that the contribution does not violate any intellectual property rights of third parties.
- [ ] I confirm that I have added license headers to all of the files I am contributing (with a license of my choice)
- [ ] Change pull request label to 'Waiting for review' 

Note: for an example of a contribution, where a license header, description, data link and CIL version has been added, please
see: [example_contribution](https://github.com/TomographicImaging/CIL-User-Showcase/blob/main/example_contribution)

### CODE REVIEW

**Comment by MargaretDuff** [comment]
Many thanks @IdaPug - I am just checking through this notebook and it looks brilliant! I will suggest a few changes but firstly, do you know where the image of the glass tubes in the metal holder comes from? Do we have permission to use it?

**Comment by MargaretDuff** [comment]
https://github.com/IdaPug/CIL-User-Showcase/pull/2

**Comment by IdaPug** [comment]
I have just asked the person who provided the image for permission and am waiting for a reply.  The changes looks good.

**Comment by MargaretDuff** [comment]
Hi @IdaPug - Thanks for your work on this! -  did you get an answer from the person who provided the image?

**Comment by IdaPug** [comment]
Yes! the picture is taken by the same people who provided the dataset and it is okay to use in the notebook. The people are:  Mohamad Khalil, Jan Kehres, and Wail Mustafa.

**Review by MargaretDuff — APPROVED** [review]
Seen by @MargaretDuff, @lauramurgatroyd and @jakobsj. We are happy to merge. Thanks all

**Pull request merged**
