### PR TITLE
Exciscope Polaris phase contrast reconstruction with CIL

### PR DESCRIPTION
**Pull request by rbnkrgr**
## Checklist when you are ready to request a review

- [ x] I have performed a self-review of my code
- [ x] I have created a new folder, containing my contributions which are in the form of jupyter notebooks, with any necessary supporting python files, and a LICENSE file.
- [x] I have added a description of my contribution(s) to the top of my file(s)
- [x] If publicly available, I have added a link to the dataset used near the top of my file(s)
- [x] I have added the CIL version I ran with near the top of my file(s)
- [ x] The content of this Pull Request (the Contribution) is intentionally submitted for inclusion in CIL-User-Showcase.
- [ x] I confirm that the contribution does not violate any intellectual property rights of third parties.
- [x] I confirm that I have added license headers to all of the files I am contributing (with a license of my choice)
- [ x] Change pull request label to 'Waiting for review' 

Note: for an example of a contribution, where a license header, description, data link and CIL version has been added, please
see: [example_contribution](https://github.com/TomographicImaging/CIL-User-Showcase/blob/main/example_contribution)

### CODE REVIEW

**Comment by MargaretDuff** [comment]
Hi @rbnkrgr - thank you for submitting your showcase! I understand you will be updating it so we won't review it yet. Please let us know if there is anything we can do to help :)

**Comment by rbnkrgr** [comment]
Hi @MargaretDuff , we updated the file and from our side that is the final version.

Thank you and let us know if we should change anything.

**Comment by MargaretDuff** [comment]
> Hi @MargaretDuff , we updated the file and from our side that is the final version.
> 
> Thank you and let us know if we should change anything.

Brilliant - I will take a look next week :)

**Comment by MargaretDuff** [comment]
Dear @rbnkrgr! Thanks so much for your contribution. It looks like a really interesting dataset (thank-you as well for putting this on zenodo) and a good demonstration of the CIL processors and phase contrast reconstruction. 

I have just added the CIL version and a small explanation about where someone running the notebook needs to change data paths. 

I wonder if you could add any more explanation of what differences you are seeing between the different images, why the phase contrast reconstruction is useful and also what effect the different delta values are having. This doesn't need to be much, but maybe a sentence or two after some of the image plots. 

When I run the notebook, I get an error with the last cell, the qim3d viewer, 
image. I have not used qim3d before, do you have any ideas?

**Comment by rbnkrgr** [comment]
Hi @MargaretDuff , as you suggested I added some explanations to the phase retrieval and the comparison between different phase retrieval parameters. I hope that comments are clear.

The qim library is a package for Quantitative Imaging in 3D which has some nice features for data loading and visualization (https://platform.qim.dk/qim3d/). This cell is a interactive 3d visualization cell which I guess uses in the background some kind of browser protocols. I am not an expert in that either. You have a tried that in vscode right? It could be that this cell just works when used in a browser.
But from my side we could as well remove that part.

**Review by hrobarts — APPROVED** [review]
Hi @rbnkrgr this notebook looks great, I like how you show the effect of different delta/beta values in the phase retrieval. I'm happy to approve it as is. I just had one suggestion: I think you're using the default delta value (=1) in the Large Delta Value phase retrieval, it might be better to explicitly pass delta=1 so it's clear which value you're using.

Also to note, the qim3d visualisation did work for me in vscode. It looks like a really nice visualisation tool so it would be good to get to bottom of why it wasn't rendering for Margaret.

**Comment by hrobarts** [comment]
One other thing - if you have any advice on how you tuned the parameters for the RingRemover that would also be nice to add.

**Comment by MargaretDuff** [comment]
Thanks for reviewing Hannah - @rbnkrgr - are you happy for us to merge this or would you like to add some advice on how you tuned the parameters for the ring remover? We are happy either way

**Comment by rbnkrgr** [comment]
Thanks for reviewing @hrobarts !
I added now the delta = 1 as you suggested.
For the Ring Removal  we haven't tested any settings and used in that case just the processor with standard settings, so here I don't have special advice to give.
I am happy with you merging this @MargaretDuff .

**Comment by hrobarts** [comment]
Thanks for the updates @rbnkrgr, it's all looking good to me. @MargaretDuff are you happy to merge?

**Comment by MargaretDuff** [comment]
Excellent - many thanks @rbnkrgr- an excellent notebook and contribution!

P.s. I also got qim3d working
image

**Pull request merged**
