### PR TITLE
Multibang

### PR DESCRIPTION
**Pull request by MargaretDuff**
## Describe your contribution

Multibang user case from Sean Holman. Margaret and Gemma have added the license, tidied up some of the markdown, added the location of the data and showed the effect of changing regularisation parameters for the HTC data. 

## Checklist when you are ready to request a review

- [X ] I have performed a self-review of my code
- [X ] I have created a new folder, containing my contributions which are in the form of jupyter notebooks, with any necessary supporting python files, and a LICENSE file.
- [X ] I have added a description of my contribution(s) to the top of my file(s)
- [X ] If publicly available, I have added a link to the dataset used near the top of my file(s)
- [ X] I have added the CIL version I ran with near the top of my file(s)
- [X ] The content of this Pull Request (the Contribution) is intentionally submitted for inclusion in CIL-User-Showcase.
- [ X] I confirm that the contribution does not violate any intellectual property rights of third parties.
- [X ] I confirm that I have added license headers to all of the files I am contributing (with a license of my choice)
- [X ] Change pull request label to 'Waiting for review' 

Note: for an example of a contribution, where a license header, description, data link and CIL version has been added, please
see: [example_contribution](https://github.com/TomographicImaging/CIL-User-Showcase/blob/main/example_contribution)

### CODE REVIEW

**Review by jakobsj — CHANGES_REQUESTED** [review]
Looks good to me, only I'd suggest putting "Edited by ..." on a separate line, and if you can restart and restart from a fresh kernel, as the output line numbers currently starts with [124...].

**Comment by jakobsj** [comment]
Also, I had envisioned this to have the number 001, as it was the first we received.

**Comment by MargaretDuff** [comment]
Thanks @jakobsj - I have made those changes

**Review by jakobsj — APPROVED** [review]
Looks ready to merge!

**Pull request merged**
