### PR TITLE
Dyn mr recon hackathon

### PR DESCRIPTION
**Pull request by ckolbPTB**
## Checklist when you are ready to request a review

- [x] I have performed a self-review of my code
- [x] I have created a new folder, containing my contributions which are in the form of jupyter notebooks, with any necessary supporting python files, and a LICENSE file.
- [x] I have added a description of my contribution(s) to the top of my file(s)
- [x] If publicly available, I have added a link to the dataset used near the top of my file(s)
- [x] I have added the CIL version I ran with near the top of my file(s)
- [x] The content of this Pull Request (the Contribution) is intentionally submitted for inclusion in CIL-User-Showcase.
- [x] I confirm that the contribution does not violate any intellectual property rights of third parties.
- [x] I confirm that I have added license headers to all of the files I am contributing (with a license of my choice)
- [x] Change pull request label to 'Waiting for review' 

Note: for an example of a contribution, where a license header, description, data link and CIL version has been added, please
see: [example_contribution](https://github.com/TomographicImaging/CIL-User-Showcase/blob/main/example_contribution)

### CODE REVIEW

**Comment by MargaretDuff** [comment]
@lauramurgatroyd  or @jakobsj - I think this is ready to merge if you are happy

**Review by jakobsj — APPROVED** [review]
Looks great, thanks a lot @ckolbPTB, @Letizia97 and @MargaretDuff!

**Comment by MargaretDuff** [comment]
@lauramurgatroyd  - if you are happy can you merge? I don't have write access :)

**Comment by lauramurgatroyd** [comment]
I'll give you access 😎

**Pull request merged**
